# Generated by Django 4.2.3 on 2023-07-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0004_cliente_producto_remove_clientes_pais_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
