# Generated by Django 4.2.3 on 2023-07-25 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_remove_cliente_producto_delete_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuarios',
        ),
    ]
