# Generated by Django 4.2.3 on 2023-08-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_rename_cliente_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='ciudad',
        ),
    ]
